// Regenera notes.js desde el guion (y actualiza la copia guion.md). Run: node build-notes.mjs
import fs from 'fs';
const SRC='/Users/tk/Documents/Codex/2026-09-08/what-happened-relevant-to-ai-safety/charla-unsam/guion-universidad-solo-texto.md';
const LOCAL=new URL('./guion.md',import.meta.url);
const md=fs.existsSync(SRC)?fs.readFileSync(SRC,'utf8'):fs.readFileSync(LOCAL,'utf8');
fs.writeFileSync(LOCAL,md);
const notes=md.split(/^## Diapositiva /m).slice(1).map(b=>{const [head,...rest]=b.split('\n');const [num,title]=head.split(' · ');return {num:+num,title:title.trim(),text:rest.join('\n').trim().split(/\n\s*\n/)};});
fs.writeFileSync(new URL('./notes.js',import.meta.url),'// generated by build-notes.mjs from guion-universidad-solo-texto.md\nexport const NOTES='+JSON.stringify(notes,null,1)+';\n');
console.log(notes.length,'slides');
